
naver-cloud-sms.accessKey = wyqWEPbhYZMhTOeQUTIa

naver-cloud-sms.secretKey = ny0zL8JQmnaDC5udrrGEL4cvws390VLPkw6tlj9L

naver-cloud-sms.serviceId = ncp:sms:kr:308123185077:sms_module

naver-cloud-sms.senderPhone = 01080203681